Chore/repo improves
hubtype/botonic pull request #1037
Opened 2020-10-28 13:24 UTC by vanbasten17

## Description
Little improvements to our repo:
* Fix broken links for Botonic Logo
* Add License: MIT to every package
* Add keywords to every package (to be more searchable by `npm search` and `npm`)

2020-10-28 14:04 UTC, MarcosCA requested changes

2020-10-28 14:04 UTC, MarcosCA commented on README.md
> +    <img alt="Node.js" src="https://botonic.io/img/botonic-logo.png"f width="150"/>
.png"f
that "f" ?

2020-10-28 14:04 UTC, MarcosCA commented on packages/botonic-plugin-watson/package.json
> +    "segment"
is correct segment here?

2020-10-28 14:25 UTC, vanbasten17 commented on packages/botonic-plugin-watson/package.json
> +    "segment"
good catches, fixed 👍

2020-10-28 14:35 UTC, MarcosCA approved these changes

2020-10-29 09:46 UTC, asastre approved these changes
Nice update!
Would it be better to use words in singular rather than plural as keywords? I've search a little bit but I haven't found any clear information about it.

2020-10-29 14:28 UTC, merged