chore(nlp): Greek tokenizer, stemmer and stopwords added
hubtype/botonic pull request #1110
Opened 2020-11-18 16:34 UTC by elozano98

## Description

Greek **tokenizer**, **stemmer**, and **stopwords** have been added to contentful nlp.

## Context

Adding them will make it possible to process Greek text.

## Approach taken / Explain the design

The tokenizer and the stemmer used are from the [nlpjs](https://github.com/axa-group/nlp.js/tree/master/packages/lang-ro) library while the stopwords have been collected from the [nltk](https://www.nltk.org/) python library.

## Testing

The pull request...

- :heavy_check_mark: has unit tests

2020-11-18 17:10 UTC, vanbasten17 approved these changes

2020-11-19 10:33 UTC, dpinol requested changes

2020-11-19 10:33 UTC, dpinol commented on packages/botonic-plugin-contentful/src/nlp/stopwords/stopwords-el.ts
> +export const elDefaultStopWords = [
same as https://github.com/hubtype/botonic/pull/1109#discussion_r526754178

2020-11-19 13:21 UTC, dpinol approved these changes

2020-11-19 14:35 UTC, merged