Chore/improve telemetry
hubtype/botonic pull request #1243
Opened 2021-01-11 13:21 UTC by vanbasten17

## Description
* Added `BOTONIC_DISABLE_ANALYTICS` secret to the repo and in its corresponding workflow
* Improved analytics by retrieving `@botonic/cli`'s version and `@botonic` dependencies.
* Refactored json logic and renamed linter suggestions.

## Context
`BOTONIC_DISABLE_ANALYTICS` should be declared in order to not track installations run by Github Actions, because they can add noise to the analytics.

## Next steps
Once this PR is approved, I'm gonna apply these changes also in `botonic-examples` track methods. Unifying and improving error messages in related @ericmarcos task: https://linear.app/hubtype/issue/BOT-171/better-understand-1st-time-developer-flow

2021-01-12 07:11 UTC, manuelfidalgo commented
LGTM! :ok_hand:

2021-01-12 07:13 UTC, manuelfidalgo approved these changes
:ok_hand:

2021-01-12 14:16 UTC, dpinol requested changes

2021-01-12 14:16 UTC, dpinol commented on packages/botonic-cli/src/utils.ts
> +async function sh(cmd: string) {
type return to 
`{ stdout: string, stderr: string }`

2021-01-12 14:52 UTC, ericmarcos approved these changes

2021-01-12 14:52 UTC, ericmarcos commented on .github/workflows/botonic-cli-tests.yml
> +          BOTONIC_DISABLE_ANALYTICS: ${{ secrets.BOTONIC_DISABLE_ANALYTICS }}
agree

2021-01-14 09:50 UTC, vanbasten17 commented on .github/workflows/botonic-cli-tests.yml
> +          BOTONIC_DISABLE_ANALYTICS: ${{ secrets.BOTONIC_DISABLE_ANALYTICS }}
sure, changed 👍

2021-01-14 09:54 UTC, vanbasten17 commented on packages/botonic-cli/src/utils.ts
> +    if (fs.existsSync(botonicCredentialsPath)) {
good catch, this is unnecessary 👍

2021-01-14 09:55 UTC, vanbasten17 commented on packages/botonic-cli/src/utils.ts
>        console.warn('Credentials could not be loaded', e)
it is provided 👍

2021-01-14 09:56 UTC, vanbasten17 commented on packages/botonic-cli/src/utils.ts
> +    return undefined
added 👍

2021-01-14 12:25 UTC, merged