Chore/improve telemetry
hubtype/botonic pull request #1290
Opened 2021-02-01 16:42 UTC by vanbasten17

## Description

* Track which template has been selected by the developer.
* Track errors when running botonic new.
* Remove build step after running `botonic new`. (It will improve DX and it does not make sense at all)

2021-02-01 16:58 UTC, dpinol commented on packages/botonic-cli/src/commands/new.ts
> +      trackError('Created Botonic Bot CLI', {
Created or Creating?

2021-02-01 17:11 UTC, dpinol requested changes

2021-02-01 17:11 UTC, dpinol commented on packages/botonic-cli/src/commands/new.ts
> +      trackError('Created Botonic Bot CLI', {
since we always want an error arg for trackError, I prefere that it has 3 arguments: eventName, error, and optional properties

2021-02-01 17:11 UTC, dpinol commented on packages/botonic-cli/src/commands/new.ts
> +      trackError('Created Botonic Bot CLI', {
Or we can just name it "Failed creation ..." or "Not created..." and drop the initial "Error:" injected in trackError

2021-02-01 22:44 UTC, asastre approved these changes
I agree with @dpinol comments, I think it will be better to change a little bit the naming of the errors.

2021-02-01 22:44 UTC, asastre commented on packages/botonic-cli/src/utils.ts
> +  console.log({ event }, { properties })
Remove this console.log if not needed.

2021-02-02 08:00 UTC, ericmarcos requested changes

2021-02-02 08:14 UTC, vanbasten17 commented on packages/botonic-cli/src/utils.ts
> +  track(`Error: ${event}`, properties)
sure, makes sense, applied 👍

2021-02-02 10:02 UTC, MarcosCA approved these changes

2021-02-02 10:08 UTC, merged