feat(botonic-plugin-contentful): add indicationText parameter
hubtype/botonic pull request #1291
Opened 2021-02-02 15:10 UTC by AlbertGom

## Description
Added a new field named indicationText in cms queue. This field is used to show a message before a handoff and it is placed in desk queue contentful content model.

## Context
In decathlon bot we are using it and we need to have it in the plugin.

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2021-02-05 09:17 UTC, dpinol requested changes

2021-02-05 09:17 UTC, dpinol commented on packages/botonic-plugin-contentful/src/cms/contents.ts
> +    readonly indicationText?: string
please confirm with somebody from enterprise (Candice) or with a native speaker (Gordon?) that this is the best name for this concept. 
my brainstorm:  handoffMessage

2021-02-05 09:17 UTC, dpinol commented on packages/botonic-plugin-contentful/src/contentful/queue.ts
>  }
always create or extend a unit test when you modify a library
You can extend packages/botonic-plugin-contentful/tests/contentful/contents/queue.test.ts

2021-02-09 13:09 UTC, vanbasten17 approved these changes
check @dpinol 's feedback and go for it 👍

2021-02-12 11:43 UTC, AlbertGom commented
I have created another PR: https://github.com/hubtype/botonic/pull/1309 of a branch that comes from master instead of develop.

2021-02-12 11:43 UTC, closed without merging