Chore/dialogflow config ts jest codecov #PLA-375
hubtype/botonic pull request #1374
Opened 2021-03-16 17:04 UTC by manuelfidalgo

## Description
Configure the following in botonic-plugin-dialogflow:
- Convert index.js to typescript
- Add Jest config and create a unit test
- Use codecov to track coverage

## Context
In order to track coverage for botonic, we needed to configure jest, create a test and configure codecov.
Also, since this package is quite small, we also migrated it to typescript.

## To document / Usage example
Final report can be seen here: https://codecov.io/gh/hubtype/botonic/tree/8e2cba1d82a2ac4f6e27f08262e33332fbe66ef9/packages

## Testing

The pull request...

- has unit tests? It includes a simple unit test to check coverage
- has integration tests: I tested manually with a bot and real dialogflow configuration

## Note
Big thanks to @marcrabat for helping me with this one!

2021-03-16 20:02 UTC, dpinol requested changes
welcome to the TS fans club! :clubs:

2021-03-16 20:02 UTC, dpinol commented on packages/botonic-plugin-dialogflow/src/types.ts
> +export class Request {
you could declare @botonic/core as devdependency to import this type (which is actually the interface BotRequest)

2021-03-16 20:02 UTC, dpinol commented on packages/botonic-plugin-dialogflow/tsconfig.json
> +    "outDir": "dist"
change to lib

2021-03-17 17:21 UTC, manuelfidalgo reviewed
@dpinol,  Marc helped me with converting this package to TS and we checked against a new created bot, so I'm not aware if there is any other case that could case breaking changes. @marcrabat ?

2021-03-22 12:50 UTC, dpinol commented on .github/workflows/botonic-plugin-dialogflow-tests.yml
> +  botonic-plugin-dialogflow:
:clap:

2021-03-22 13:22 UTC, vanbasten17 approved these changes
Nice job!! 👏 👏 👏

2021-03-22 17:17 UTC, dpinol requested changes

2021-03-26 10:51 UTC, manuelfidalgo commented on packages/botonic-plugin-dialogflow/src/index.ts
> +  sessionID: string
done!

2021-03-26 10:52 UTC, manuelfidalgo commented on packages/botonic-plugin-dialogflow/src/index.ts
> +import { BotRequest } from '@botonic/core/src'
ok! I removed it in that file and also in the tests.
I also added // eslint-disable-next-line import/named since eslint was complaining

2021-03-26 12:22 UTC, manuelfidalgo commented on packages/botonic-plugin-dialogflow/src/index.ts
> +      iss: creds.clientEmail,
I reverted those changes because the fields were not being correctly mapped making the integration with dialogflow was failing.

2021-04-06 09:05 UTC, dpinol approved these changes

2021-04-06 10:01 UTC, merged