docs: new entry about webchat connection and disconnection
hubtype/botonic pull request #1380
Opened 2021-03-19 16:37 UTC by annehubtype

Please review:

- New menu entry added under **Webchat > Connectivity**
- **sidebars.json** updated for doc tool purpose.
- **webchat-api** updated with `Botonic.isOnline()`

## Description

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2021-03-20 10:28 UTC, vanbasten17 requested changes

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-api.md
> +- `Botonic.isOnline(boolean)`: Sets the webchat connection status.
`Gets the webchat connection status to know whether is connected (`true`) or not (`false`)`.

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-connectivity.md
> +Sometimes, the connection can be lost between the server and the chatbot. To handle this situation, you can set specific parameters to quickly detect the connection issue.
To handle this situation, you can set specific parameters to tune how to detect the connection issue.

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-connectivity.md
> +To do so:
To do so, you can configure the server options to tune timings for resolving Webchat's connection.

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-connectivity.md
> +1. Set the `Botonic.isOnline()` method. Values are `true` or `false` depending on your server configuration.
Change `To do so` above with the mentioned suggestion or similar and remove these two points. The first one is not accurated.

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-connectivity.md
> +You can use a function if you prefer. For example, if you want to display the warning message in various languages:
if you want to display the warning message depending on the language:

2021-03-20 10:28 UTC, vanbasten17 commented on docs/docs/webchat/webchat-connectivity.md
> +3. Add the `errorMessage` variable to change the warning message when a connection issue occurs.
Remove this point and add a description like:
`To define the message to be displayed when webchat experiences connecitivity issues you can use `errorMessage``

2021-03-22 13:30 UTC, vanbasten17 approved these changes

2021-03-29 10:01 UTC, vanbasten17 commented on docs/docs/webchat/webchat-api.md
> +- `Botonic.isOnline(boolean)`: Gets the webchat connection status to know whether it is connected (true) or not (false).
`Botonic.isOnline(boolean)` --> ``Botonic.isOnline()``

2021-04-01 11:47 UTC, ericmarcos requested changes
As a developer I'd like to see a more general description of what the framework supports in terms of connectivity, how does it do it, and finally what options do I have to personalise this behaviour. For example:

Botonic comes with offline support, meaning that messages sent / received while the user loses connection are not lost. Instead, they're stored in a queue and are re-sent once connection is recovered. Botonic detects if the user is online/offline by sending ping-pong messages through the websocket connection with the server. By default, Botonic sends a "ping" every 20 seconds and waits for a "pong" response for 5 seconds, if this response is not received then a "Connection issues" indicator is shown to the user (screenshot).
You can customize this behaviour...

2021-04-01 11:47 UTC, ericmarcos commented on docs/docs/webchat/webchat-connectivity.md
> +Sometimes, the connection can be lost between the server and the chatbot. To handle this situation, you can set specific parameters to detect the connection issue.
"between the server and the **chatbot**" -> "between the server and the **webchat**"

2021-04-01 11:47 UTC, ericmarcos commented on docs/docs/webchat/webchat-connectivity.md
> +- `activityTimeout`: Time to wait (in ms) before pinging the server to know if the connection is still working. Default value: 20 * 1000.
Default value 20 seconds (20*1000)

2021-04-01 11:47 UTC, ericmarcos commented on docs/docs/webchat/webchat-connectivity.md
> +- `pongTimeout`: After pinging the server, time to wait (in ms) before assuming the connection is lost and closing it. Default value: 5 * 1000.
Default value 5 seconds (5*1000)

2021-04-01 11:47 UTC, ericmarcos commented on docs/docs/webchat/webchat-connectivity.md
> +       if(locale === 'es') return 'Problemas de conexión'
This variable is not defined anywhere, I don't like when documentation examples give me incomplete code

2021-06-20 10:12 UTC, ericmarcos approved these changes

2021-07-08 09:21 UTC, merged