feat(ner-plugin): Postprocess implemented
hubtype/botonic pull request #1394
Opened 2021-03-22 12:46 UTC by elozano98

**Depends on #1393.** Please, review it first. :warning: 

## Description
A `PredictionProcessor` has been implemented to process the output tensor generated by the model prediction.

## Context
The `PredictionProcessor` takes the sequence and the output tensor of the model to generate an array that contains the recognized entities.

## Approach taken / Explain the design
The `PredictionProcessor` maps the sequence with the output tensor to get the recognized entities and the corresponding confidences for all possible entity labels.

## Testing

The pull request...

- [x] has unit tests

2021-03-23 16:48 UTC, dpinol requested changes

2021-03-24 10:38 UTC, elozano98 commented on packages/botonic-plugin-ner/src/postprocess/prediction-processor.ts
> +export class PredictionProcessor {
I agree this needs a refactor but just to know, when this type of refactoring is requested in a PR, what should I do?

- Apply the refactor here. Including the `InputGenerator` refactor.
- Apply the `InputGenerator` refactor in the #1393 PR and the `PredictionProcessor` refactor in this PR.
- Close all chain PR and then, apply the requested refactor.

Which one is the best option? @dpinol

2021-03-24 11:06 UTC, elozano98 commented on packages/botonic-plugin-ner/src/postprocess/prediction-processor.ts
> +export class PredictionProcessor {
Added this refactor to my TODO list.

2021-03-24 15:56 UTC, vanbasten17 approved these changes

2021-03-30 10:52 UTC, dpinol approved these changes

2021-03-30 11:35 UTC, merged