Feat/contentful export 0.18.0
hubtype/botonic pull request #1421
Opened 2021-04-01 13:43 UTC by AinaVendrell

## Description
Add contentful export file of the version 0.18.0

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2021-04-06 12:31 UTC, vanbasten17 approved these changes

2021-04-06 12:46 UTC, dpinol requested changes
I think it doesn't make sense my initial decision to keep the export json with separate filenames. We have git history for this.
Can you please do the following in separate commits so that hopefully the intercommit diffs show us the differences:

1. remove version 0.9.22 of the json. git mv contentful-export-0.11.3.json to contentful-export.json.
2. git rm contentful-export.json and git mv contentful-export-0.18.0.json to contentful-export.json

2021-04-12 09:54 UTC, dpinol approved these changes

2021-04-13 07:37 UTC, vanbasten17 approved these changes

2021-04-13 09:50 UTC, merged