feat(nlp): Text Classification - PredictionProcessor
hubtype/botonic pull request #1442
Opened 2021-04-09 10:54 UTC by elozano98

## Description
Implementation of the class needed to process the model output.

## Context
We need to process the output tensor so we can obtain the intents and their confidences.

## Testing
The pull request...
 - [x] has unit tests

2021-04-09 13:46 UTC, dpinol requested changes

2021-04-09 13:46 UTC, dpinol commented on packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts
> +  private generateIntents(confidences: number[]): Intent[] {
generate sounds like "create from nothing". rename to createIntents

2021-04-09 15:24 UTC, dpinol requested changes

2021-04-09 15:24 UTC, dpinol commented on packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts
> +    const intents = this.computeIntents(confidences)
compute means there's a calculation/algorithm. I don't see it here. why not createIntents?

2021-04-12 07:47 UTC, vanbasten17 approved these changes

2021-04-12 07:49 UTC, vanbasten17 commented on packages/botonic-nlp/tests/tasks/text-classification/process/prediction-processor.test.ts
> +import * as helper from '../../../helpers/tasks/text-classification/constants-helper'
Try always to import only the necessary code you need:
`import {CLASSES} from '....../constants-helper'`

2021-04-12 09:00 UTC, dpinol approved these changes

2021-04-12 10:02 UTC, merged