feat(plugin-text-classification): BotonicPluginTextClassification implemented
hubtype/botonic pull request #1472
Opened 2021-04-22 10:54 UTC by elozano98

## Description
Following the top-down approach, the first thing has been to create the plugin configuration and the main class: `BotonicPluginTextClassification`.
## Testing

The pull request...

- [ ] has unit tests
- [ ] has integration tests

2021-04-22 12:48 UTC, dpinol requested changes

2021-04-22 12:48 UTC, dpinol commented on packages/botonic-plugin-text-classification/package.json
> +    "@botonic/core": "~0.18.0",
try moving @botonic/core to devDependencies, as I think we only use types

2021-04-22 12:48 UTC, dpinol commented on packages/botonic-plugin-text-classification/src/index.ts
> +        //   Pending to be implemented.
//TODO

2021-04-22 12:48 UTC, dpinol commented on packages/botonic-plugin-text-classification/src/index.ts
> +      console.log('Cannot classify the input text')
console.error('Cannot classify the input text', e)
NEVER hide an exception details. It's also nice to log the input (request.input.data?)

2021-04-23 08:58 UTC, dpinol requested changes

2021-04-23 08:58 UTC, dpinol commented on packages/botonic-plugin-text-classification/src/index.ts
> +        if (request.input.type == INPUT.TEXT && !request.input.payload) {
line duplicated

2021-04-23 08:58 UTC, dpinol commented on packages/botonic-plugin-text-classification/src/index.ts
> +          const ner = (await this.modelsSelector).select(detectedLocale)
modelsSelector not set.

2021-04-23 09:18 UTC, dpinol approved these changes

2021-04-26 09:07 UTC, vanbasten17 approved these changes

2021-04-26 10:39 UTC, merged