docs(plugin-text-classification): Plugin Documentation
hubtype/botonic pull request #1519
Opened 2021-05-03 13:20 UTC by elozano98

## Description
Documentation of `plugin-text-classification`.

2021-05-03 15:37 UTC, dpinol requested changes
add the "document" label to the PR, and talk to Anne on what she needs for https://botonic.io/docs.
Talk to Marc on how to create a sample bot for our samples site

2021-05-03 15:37 UTC, dpinol commented on packages/botonic-plugin-text-classification/README.md
> +The plugin must be required in the `src/plugins.js` and defining the locales of trained models into the options.
"and defining the locales of trained models into the options." -> and the locales of the trained models must be defined in their options

2021-05-03 15:37 UTC, dpinol commented on packages/botonic-plugin-text-classification/README.md
> +> **Note:** The order of provided locales matters. In case locale detection fails, the first one in the array will be used as a fallback.
the provided locales

2021-05-04 08:23 UTC, annehubtype commented on packages/botonic-plugin-text-classification/README.md
> +After detecting the locale of the text, and using the corresponding model to predict the class, extra information about the intent of the user is added to the input message.
After detecting the text locale, and using the relevant model to predict the class, extra information about the user intent is added to the input message.

2021-05-04 09:21 UTC, vanbasten17 approved these changes

2021-05-04 09:21 UTC, vanbasten17 commented on packages/botonic-plugin-text-classification/README.md
> +After detecting the text locale, and using the corresponding model to predict the class, extra information about the user's intent is added to the input message.
`is added to the input object`

2021-05-04 09:21 UTC, vanbasten17 commented on packages/botonic-plugin-text-classification/README.md
> +## Install the plugin
Installing the plugin

2021-05-04 09:21 UTC, vanbasten17 commented on packages/botonic-plugin-text-classification/README.md
> +## Require the plugin
Requiring the plugin (for the docs I've seen so far, it's common to use this tense)

2021-05-04 09:21 UTC, vanbasten17 commented on packages/botonic-plugin-text-classification/README.md
> +The plugin must be required in the `src/plugins.js` and the locales of the trained models must be defined in their options.
I would say just in `src/plugins.js` or `in the src/plugins.js file`

2021-05-04 09:21 UTC, vanbasten17 commented on packages/botonic-plugin-text-classification/README.md
> +**Locales order matters.** In case locale detection fails, the first one in the array will be used as a fallback.
Talk in "positive" terms (for developer's confidence) we should not state that XXX can fail, try to rephrase it like, or similar:
> **Note:** If locale detection is ambiguous, the  locale defined first in the array will be used as a fallback.
:)

2021-05-04 10:27 UTC, annehubtype approved these changes

2021-05-04 14:17 UTC, annehubtype commented on packages/botonic-plugin-text-classification/README.md
> +You can use the information added by this plugin to create new routes in **`src/routes.js`**.
Use the information added by this plugin to create new routes in **`src/routes.js`** and start using text classification.

2021-05-05 09:27 UTC, merged