Creation of botonic-plugin-google-translate
hubtype/botonic pull request #1620
Opened 2021-06-09 14:02 UTC by elozano98

## Description
Creation of `botonic-plugin-google-translate` that detects the language of the user input text.

## Context
If you have a Google Translate API in Google Cloud, now you can use it to detect the language of the user input text.

## Approach taken / Explain the design
To use this plugin, you need to provide some of your credentials to have access to the Google Translate API:
- `Private Key Id`
- `Private Key`
- `Client Email`
- `Project Id`

## To document / Usage example
You can define a `whitelist` into plugin options to only accept specific languages as detection. In case none of the defined languages is the detected one, 'en' would be set as default.

2021-06-10 10:25 UTC, vanbasten17 approved these changes

2021-06-10 10:25 UTC, vanbasten17 commented on packages/botonic-plugin-google-translate/README.md
> +```
you can save one script sample by adding just the whitelist commented and explaining the behavior

2021-06-10 11:33 UTC, dpinol approved these changes
:clap:  excellent design!!

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +Before using this plugin, you need a project that has the Cloud Translation API enabled and its credentials. See [Cloud Translation Set Up Guide](https://cloud.google.com/translate/docs/setup).
what do you mean by a project? Is it enough to sat that you need to setup  Cloud Translation API credentials?

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +To being able of using this plugin to detect the language of the user input text, you need to have it installed and added to your plugins.
The sentence is verbose and does not add much meaning.
"You need to add the following configuration to your bot's plugins"

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +> **Note:** This is case-sensitive so make sure to correctly define your credentials.
what is "This" ? the configuration fields?

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +If this whitelist is defined and none of the specified languages match the detected ones, `'en'` will be set as default.
match -> matches

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +If this whitelist is defined and none of the specified languages match the detected ones, `'en'` will be set as default.
"will be set as default" -> "will be selected"

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +If you want to check the language of the user input text, you only need to take a look at the `__locale` variable of the current session.
replace with st like "The plugin will set the `__locale` field of the bot request session. The session is available in your bot's routes and in the request object passed to your bot actions' botonicInit function."

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +This plugin uses [Google Cloud Translation API](https://cloud.google.com/translate) to detect the language of the user input text.
specify which iso is used. Since we set in locale field, be explicit here on whether the country is ever set (only "es" or sometimes "es_ES"?

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/package.json
> +    "@types/webgl2": "0.0.6"
what is this for?

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/src/access-token.ts
> +  private readonly header
add string types

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +This plugin uses [Google Cloud Translation API](https://cloud.google.com/translate) to detect the language of the user input text.
since the plugin contains the word translate, make explicit that the plugin does not yet have an API to translate text

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/src/index.ts
> +      console.log('Cannot use Google Cloud Translate API', e)
console.error
"Error detecting language with  Google Cloud Translate API"

2021-06-10 11:33 UTC, dpinol commented on packages/botonic-plugin-google-translate/README.md
> +If this whitelist is defined and none of the specified languages match the detected ones, `'en'` will be set as default.
add an defaultLanguage field in pluginOptions.
Otherwise, bots won't be able to differentiate between "I don't know the language" and "english"

2021-06-10 11:34 UTC, dpinol requested changes
apply comments

2021-06-11 08:50 UTC, elozano98 commented on packages/botonic-plugin-google-translate/package.json
> +    "@types/webgl2": "0.0.6"
Not needed, I just removed it.

2021-06-11 09:02 UTC, elozano98 commented
I will apply all required changes of the README file in the [next PR](https://github.com/hubtype/botonic/pull/1624) since the functionality changes a bit when adding the translation feature to the plugin. @dpinol @vanbasten17

2021-06-11 13:55 UTC, dpinol approved these changes

2021-06-11 14:30 UTC, merged