chore(nlu/plugin-nlu): remove legacy nlu packages and workflows
hubtype/botonic pull request #2005
Opened 2021-11-02 10:52 UTC by vanbasten17

## Description
* Removed nlu and botonic-plugin-nlu packages to be deprecated later on from `master-lts` branch.
* Removed workflows for these packages.

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2021-11-02 10:57 UTC, elozano98 approved these changes

2021-11-02 11:45 UTC, manuelfidalgo requested changes
Everything good so far, but I think there some other parts where nlu references should removed (not sure if this is the PR to change all of them):
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- docs/docs: create-convapp.md faq.md project-structure.md...

2021-11-03 10:26 UTC, vanbasten17 commented
yes @manuelfidalgo , I will write a task for this, but out of the scope of this PR, as we will need to update the docs.

2021-11-03 10:31 UTC, manuelfidalgo approved these changes
:rocket:

2021-11-03 10:40 UTC, merged