Feature: Flag to enable has_sense detection on plugin-hubtype-babel
hubtype/botonic pull request #2288
Opened 2022-12-02 13:18 UTC by elozano98

## Description

Added a flag that indicates if `has_sense` prediction should be applied.

2022-12-02 14:25 UTC, gbarba requested changes

2022-12-02 14:25 UTC, gbarba commented on packages/botonic-plugin-hubtype-babel/src/index.ts
> +          request.input.hasSense = response.data['has_sense']
so now the `input.hasSense` might be there or not, maybe this is undesirable and we prefer to put a `true` if no has_sense is provided by endpoint? or type properly this `input` to indicate this field might not exists

2022-12-02 14:25 UTC, gbarba commented on packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
> +  async inference(text: string, accessToken: string, hasSenseEnabled: boolean) {
I don't think the `Enabled` is a good naming but better `includeHasSense` (see https://github.com/metis-ai/hubtype-backend/pull/1270/files#r1038188933).
also add a return type whith is an object with `intents` and, **optionally** `has_sense` boolean

2022-12-07 15:05 UTC, gbarba approved these changes

2022-12-12 11:33 UTC, elozano98 commented
Need to release new `botonic-core` and `botonic-pluguin-hubtype-babel`.

2022-12-13 09:02 UTC, merged