Feature/blt 256 task flow builder plugin calls tracking plugin
hubtype/botonic pull request #2618
Opened 2023-09-18 09:26 UTC by Iru89

## Description
Plugin-flow-builder and plugin-knowledge-bases:
- Change the type of sources in the knowledge base inference response (it was not typed correctly)

Plugin-flow-builder:
- Adds botAiKnowladgeBase event tracking when the bot response is obtained from the inference with the knowledge base
- Refactor: a small problem with the suffix on payloads. When adding a suffix to all payloads when creating a button in flow builder, in the routes we don't always have the expected payload. To solve this I remove this suffix in the pre function of the plugin, this way in the routes we have the "clean" payload. 

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2023-09-19 09:04 UTC, elozano98 requested changes
Replace all Knowledge* naming prefixes by KnowledgeBase*

2023-09-19 09:40 UTC, Iru89 commented
> Replace all Knowledge* naming prefixes by KnowledgeBase*

I have also renamed inside the plugin-knowledge-bases the function getIaResponse to getInference. 
This way I think it's clearer to use-it will look like `pluginKnowledgeBases.getInference(session)`

2023-09-19 11:00 UTC, elozano98 approved these changes

2023-09-21 15:27 UTC, MarcosCA approved these changes

2023-09-26 08:28 UTC, merged