plugin-flow-builder: create contents with map
hubtype/botonic pull request #2863
Opened 2024-06-27 10:58 UTC by Iru89

## Description

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2024-07-02 08:05 UTC, asastre requested changes
Just a 1 change, the rest LGTM

2024-07-02 08:05 UTC, asastre commented on packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
> +    }
Change: You're missing the image sources to be obtanined also.
```suggestion
    for (const [key, contentId] of Object.entries(mapContents)) {
     
      contentsObject[key] = imageContents?.find(imageContent => imageContent.code === contentId) ? getImageSrc(contentId) :  getTextContent(contentId)
    }
```

2024-07-08 08:34 UTC, vanbasten17 approved these changes
nice feature!

2024-07-08 08:34 UTC, vanbasten17 commented on packages/botonic-plugin-flow-builder/src/webview/contents-context.ts
> +*/
better to have this documented in the readme, instead of here

2024-07-09 14:35 UTC, merged