botonic-react: add whatsapp product list component
hubtype/botonic pull request #2956
Opened 2024-12-24 14:42 UTC by AlbertGom

## Description

## Context

## Approach taken / Explain the design

## To document / Usage example

## Testing

The pull request...

- has unit tests
- has integration tests
- doesn't need tests because... **[provide a description]**

2025-01-15 08:42 UTC, vanbasten17 requested changes

2025-01-15 08:42 UTC, vanbasten17 commented on packages/botonic-react/src/components/whatsapp-product-list.tsx
> +  product_items: ProductItem[]
for consistency with the api you are defining, I would put productItems instead of product_items and later do the conversion to what backend will use.

2025-01-15 08:42 UTC, vanbasten17 commented on packages/botonic-react/src/components/whatsapp-product-list.tsx
> +        sections={JSON.stringify(props.sections)}
here you can map from camel to snake case the properties you are expecting

2025-01-16 22:17 UTC, AlbertGom commented
@vanbasten17 @Iru89 requested changes applied in [this PR](https://github.com/hubtype/botonic/pull/2965) in [this commit](https://github.com/hubtype/botonic/pull/2965/commits/32d7380f1fd5e39236bbe8f7d491c6a098d0e9de).

2025-01-20 07:45 UTC, vanbasten17 commented on packages/botonic-react/package.json
> +    "@babel/helper-simple-access": "^7.25.9",
If this is really needed, not sure at all, might it go to devDependencies?

2025-01-20 12:41 UTC, Iru89 approved these changes

2025-01-28 12:05 UTC, merged