fix(react): custom message types to support Reply
hubtype/botonic pull request #894
Opened 2020-08-07 10:27 UTC by ericmarcos

## Description

This PR fixes a crash that happened when using Custom Message Types together with Reply component.

Imagine you have this custom message:

```javascript
import React from 'react'
import { WebchatContext } from '@botonic/react'
import { customMessage } from './custom-message'

class MyMessage extends React.Component {
  static contextType = WebchatContext

  render() {
    return (
      <>
        <button
          onClick={() =>
            this.context.sendText(`Bye!`)
          }
        >Click me!</button>
        <p>{this.props.children}</p>
      </>
    )
  }
}

export default customMessage({
  name: 'my-message',
  component: MyMessage,
})
```

Now you can use it in your actions like this:

```javascript
import React from 'react'
import { Reply } from '@botonic/react'
import MyMessage from '../webchat/MyMessage'

export const CalendarAction = props => (
	<MyMessage>
		Hi
		<Reply payload='p'>Peperoni</Reply>
		<Reply payload='v'>Veggie</Reply>
	</MyMessage>
)
```

## Context

This problem was reported by some of our partners and users in our Slack channel

## Approach taken / Explain the design

I used the same approach that `@botonic/react/src/components/services message.jsx`

## To documentate / Usage example

See above

## Testing

The pull request...

- [ ] has unit tests
- [ ] has integration tests
- [ ] doesn't need tests because... **[provide a description]**

2020-09-04 10:24 UTC, dpinol commented
@ericmarcos any comments on my feedback?

2020-09-04 10:39 UTC, ericmarcos commented
> @ericmarcos any comments on my feedback?

@dpinol what feedback?

2020-09-04 13:08 UTC, dpinol requested changes
haha, I hadn't published my comments

2020-09-07 15:16 UTC, asastre approved these changes
Take a look at @dpinol's comments, the rest is ok!

2020-09-25 11:01 UTC, vanbasten17 approved these changes

2020-09-28 08:57 UTC, merged