fix(react): missing deep merge user-session refs
hubtype/botonic pull request #973
Opened 2020-10-02 15:31 UTC by vanbasten17

_Set as [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) if it's not ready to be merged_.  

[PR best practices Reference](https://blog.codeminer42.com/on-writing-a-great-pull-request-37c60ce6f31d/)

## Description
Missing deep merge.

2020-10-05 08:00 UTC, dpinol requested changes

2020-10-05 08:00 UTC, dpinol commented on packages/botonic-react/src/webchat/webchat.jsx
> +    updateUser(merge(webchatState.user, user))
same as with updateUser above.
btw, if updateAllUserReferences &  updateUser are identical, please

2020-10-05 08:01 UTC, dpinol commented
btw, can you remove
"Set as Draft PR if it's not ready to be merged.

PR best practices Reference"
when creating a new PR? It's only for reference

2020-10-05 10:56 UTC, vanbasten17 commented on packages/botonic-react/src/webchat/webchat.jsx
> +    updateUser(merge(webchatState.user, user))
refactored into `updateUserWithSession`.

2020-10-05 12:40 UTC, dpinol approved these changes

2020-10-07 08:43 UTC, asastre approved these changes

2020-10-08 16:36 UTC, merged